### ISSUE TITLE
Not able to edit articles

### ISSUE THREAD

**Issue by Himujjal** [strapi/strapi-starter-gatsby-blog-v2#3]
I am not able to edit articles. When I edit and click `Save` an error comes up saying `PublishedAt` field is required

The browser console logs are:
```
2.69355630.chunk.js:1 {err: c}err: cerrors: Array(1)0: "components.Input.error.validation.required"length: 1__proto__: Array(0)inner: Array(1)0: cerrors: ["components.Input.error.validation.required"]inner: []message: "components.Input.error.validation.required"name: "ValidationError"params: {path: "publishedAt", value: Tue Aug 18 2020 11:00:00 GMT+0530 (India Standard Time), originalValue: w, label: undefined}path: "publishedAt"type: "required"value: Tue Aug 18 2020 11:00:00 GMT+0530 (India Standard Time) {}stack: "ValidationError: components.Input.error.validation.required↵    at https://himu-blog.herokuapp.com/admin/main.2c92ad92.chunk.js:1:4389329↵    at https://himu-blog.herokuapp.com/admin/main.2c92ad92.chunk.js:1:4388769↵    at async Promise.all (index 0)"__proto__: Errorlength: 1__proto__: Array(0)message: "components.Input.error.validation.required"name: "ValidationError"path: undefinedtype: undefinedvalue: Seo: {id: 8, metaTitle: "Himu's first Blog", metaDescription: "A glimpse of what wonderful pieces of surpises are going to come in the upcoming days", shareImage: {…}}category: {name: "tech", id: 2}content: "# My First Blog!↵↵Let's get started! Shall we!"created_at: "2020-08-18T00:36:44.785Z"created_by: {registrationToken: null, lastname: "Upadhyaya", blocked: null, resetPasswordToken: null, isActive: true, …}id: 7image: {size: 62.06, ext: ".jpg", width: 2133, caption: "", previewUrl: null, …}publishedAt: Tue Aug 18 2020 11:00:00 GMT+0530 (India Standard Time) {}slug: "himu-s-first-blog"status: "published"title: "Himu's first Blog"updated_at: "2020-08-18T00:36:44.902Z"updated_by: {registrationToken: null, lastname: "Upadhyaya", blocked: null, resetPasswordToken: null, isActive: true, …}user: {username: "Sarah Baker", id: 2}__proto__: Objectstack: "ValidationError: components.Input.error.validation.required↵    at https://himu-blog.herokuapp.com/admin/main.2c92ad92.chunk.js:1:1453819"__proto__: Error__proto__: Object
(anonymous) @ 2.69355630.chunk.js:1
l @ main.2c92ad92.chunk.js:1
(anonymous) @ main.2c92ad92.chunk.js:1
forEach.e.<computed> @ main.2c92ad92.chunk.js:1
n @ main.2c92ad92.chunk.js:1
l @ main.2c92ad92.chunk.js:1
Promise.then (async)
n @ main.2c92ad92.chunk.js:1
c @ main.2c92ad92.chunk.js:1
(anonymous) @ main.2c92ad92.chunk.js:1
(anonymous) @ main.2c92ad92.chunk.js:1
(anonymous) @ 2.69355630.chunk.js:1
c @ main.2c92ad92.chunk.js:1
p @ main.2c92ad92.chunk.js:1
(anonymous) @ main.2c92ad92.chunk.js:1
g @ main.2c92ad92.chunk.js:1
it @ main.2c92ad92.chunk.js:1
ot @ main.2c92ad92.chunk.js:1
ct @ main.2c92ad92.chunk.js:1
pt @ main.2c92ad92.chunk.js:1
H @ main.2c92ad92.chunk.js:1
V @ main.2c92ad92.chunk.js:1
Xt @ main.2c92ad92.chunk.js:1
Jt @ main.2c92ad92.chunk.js:1
t.unstable_runWithPriority @ main.2c92ad92.chunk.js:1
Bo @ main.2c92ad92.chunk.js:1
j @ main.2c92ad92.chunk.js:1
Kt @ main.2c92ad92.chunk.js:1

```

**Comment by lucastobrazil** [comment]
Me too!

**Comment by lucastobrazil** [comment]
It seems that if you stop it from being required, it's fine and things up date. so the problem is that the validation kills it
